### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by phanikishoreg** [phanikishoreg/dist-sys-exercises#3]
tag link: https://github.com/phanikishoreg/dist-sys-exercises/releases/tag/Final_Version_HW4

Members name:
Phani
Teo
Harpreet
Changle
Mruganka
Ashwini

**Comment by wenhuizhang** [comment]
sort is a smart idea here, i learned something from you guys , at the same time, we dont need some for loops since it is a dict :+1: 

https://github.com/wenhuizhang/dist-sys-exercises/blob/lec_3_prototype/lec-3/discovery/prototypes/DiscovServer.py
